# Generated by Django 2.2.5 on 2020-07-26 14:15

import app_account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('lname', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('university', models.PositiveSmallIntegerField(choices=[(1, 'دانشگاه آزاد کرج'), (2, 'سایر دانشگاه ها'), (3, 'دانشجو نیستم')], default=1, validators=[app_account.models.check_university], verbose_name='دانشگاه')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='پست الکترونیک')),
                ('education', models.PositiveSmallIntegerField(choices=[(1, 'دانش\u200cآموزش'), (2, 'دیپلم'), (3, 'دانشجو'), (4, 'کاردانی'), (5, 'کارشناسی'), (6, 'کارشناسی ارشد'), (7, 'دکتری')], default=5, validators=[app_account.models.check_education], verbose_name='تحصیلات')),
                ('join_uni', models.PositiveSmallIntegerField(default=98, verbose_name='سال ورودی')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه')),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, 'کاربر عادی'), (2, 'نویسنده'), (3, 'کادر انجمن'), (4, 'هیئت رئیسه انجمن'), (5, 'معاون ارشد'), (6, 'مدیرکل')], default=1, verbose_name='ناحیه کاربری')),
                ('show_profile', models.BooleanField(default=False, verbose_name='نمایش پروفایل')),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی تلگرام')),
                ('avatar', models.ImageField(default='profile-avatar/default.jpg', upload_to=app_account.models.avatar_path, verbose_name='عکس پروفایل')),
                ('birthday', models.CharField(blank=True, max_length=15, null=True, verbose_name='تاریخ تولد')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'آقا'), (2, 'خانم')], null=True, validators=[app_account.models.check_sex], verbose_name='جنسیت')),
                ('live', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'کرج'), (2, 'تهران'), (3, 'سایر')], null=True, validators=[app_account.models.check_live], verbose_name='محل زندگی')),
                ('code', models.IntegerField(default=0, verbose_name='کد امنیتی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want', models.TextField(null=True, verbose_name='توقع از انجمن')),
                ('purpose', models.TextField(null=True, verbose_name='هدف از عضویت در کادر')),
                ('skills', models.TextField(null=True, verbose_name='مهارت ها')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='تلفن همراه')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی تلگرام')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ملاقات')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='ساعت ملاقات')),
                ('DateCreate', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('state', models.SmallIntegerField(blank=True, choices=[(1, 'ارسال درخواست'), (2, 'مصاحبه'), (3, 'در صف بررسی'), (4, 'تایید نهایی'), (5, 'عدم تایید')], default=1, null=True, validators=[app_account.models.check_staff], verbose_name='وضعیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='app_account.Profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو کادر',
                'verbose_name_plural': 'اعضای کادر',
            },
        ),
    ]
