# Generated by Django 2.2.5 on 2020-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='نویسنده است'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='مدرس است'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.IntegerField(default=0, editable=False, verbose_name='کد امنیتی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_uni',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سال ورودی'),
        ),
    ]
