# Generated by Django 2.2.5 on 2020-07-26 14:15

import app_course.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('_course_state', models.PositiveSmallIntegerField(choices=[(1, 'درحال برگزاری'), (2, 'تکمیل شده'), (3, 'به زودی')], null=True, validators=[app_course.models.check_course_states1], verbose_name='وضعیت دوره')),
                ('_category', models.PositiveSmallIntegerField(choices=[(1, 'برنامه نویسی'), (2, 'فتوشاپ'), (3, 'بازی سازی'), (4, 'معرفی'), (5, 'طراحی وب'), (6, 'شبکه'), (7, 'کاربردی')], null=True, validators=[app_course.models.check_course_states], verbose_name='دسته بندی')),
                ('title', models.TextField(null=True, verbose_name='عنوان دوره')),
                ('teacher', models.CharField(max_length=128, null=True, verbose_name='مدرس دوره')),
                ('info', models.TextField(null=True, verbose_name='معرفی کوتاه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات دوره')),
                ('image', models.ImageField(null=True, upload_to=app_course.models.course_image_path, verbose_name='عکس دوره')),
                ('DateCreate', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد دوره')),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True, verbose_name='محتوای متا\u200cتگ')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوراه ها',
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title', models.TextField(null=True, verbose_name='عنوان قسمت')),
                ('length', models.CharField(max_length=10, null=True, verbose_name='مدت زمان')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات')),
                ('video_aparat', models.TextField(null=True, verbose_name='لینک آپارات')),
                ('DateCreate', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد قسمت')),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True, verbose_name='محتوای متا\u200cتگ')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_course.Course', verbose_name='انتخاب دوره')),
            ],
            options={
                'verbose_name': 'جلسات دوره',
                'verbose_name_plural': 'جلسات دوره ها',
            },
        ),
    ]
