# Generated by Django 2.2.5 on 2020-10-06 22:38

import app_main.models
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreate', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='در تاریخ')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'انجام شده'), (2, 'در حال انجام'), (3, 'در آینده')], null=True, validators=[app_main.models.check_roadmap_states], verbose_name='وضعیت')),
                ('text', models.TextField(null=True, verbose_name='توضیحات ویژگی')),
                ('link', models.CharField(blank=True, max_length=120, null=True, verbose_name='لینک صفحه')),
            ],
            options={
                'verbose_name': 'ویژگی های نقشه راه آینده',
                'verbose_name_plural': 'نقشه راه آینده',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام اسلایدر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_main.models.image_path, verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام نام خانوادگی')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('cover', models.ImageField(default='team_cover_path/default_cover.jpg', upload_to=app_main.models.team_cover_path, verbose_name='عکس پس زمینه')),
                ('avatar', models.ImageField(default='team_avatar_path/default_avatar.jpg', upload_to=app_main.models.team_avatar_path, verbose_name='عکس پروفایل')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='وب سایت')),
                ('telegram', models.CharField(blank=True, max_length=128, null=True, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, max_length=128, null=True, verbose_name='اینستاگرام')),
                ('twitter', models.CharField(blank=True, max_length=128, null=True, verbose_name='توئیتر')),
                ('linkedin', models.CharField(blank=True, max_length=128, null=True, verbose_name='لینکدین')),
                ('github', models.CharField(blank=True, max_length=128, null=True, verbose_name='گیتهاب')),
                ('dribbble', models.CharField(blank=True, max_length=128, null=True, verbose_name='دریبل')),
            ],
            options={
                'verbose_name': 'عضو تیم فنی',
                'verbose_name_plural': 'تیم فنی',
            },
        ),
        migrations.CreateModel(
            name='years_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.SmallIntegerField(choices=[(1, '1385'), (2, '1386'), (3, '1387'), (4, '1388'), (5, '1389'), (6, '1390'), (7, '1391'), (8, '1392'), (9, '1393'), (10, '1394'), (11, '1395'), (12, '1396'), (13, '1397'), (14, '1398'), (15, '1399'), (16, '1400'), (17, '1401'), (18, '1402'), (19, '1403'), (20, '1404'), (21, '1405'), (22, '1406'), (23, '1407'), (24, '1408'), (25, '1409'), (26, '1410'), (27, '1411'), (28, '1412'), (29, '1413'), (30, '1414')], default=1, null=True, verbose_name='از سال')),
                ('end_year', models.SmallIntegerField(choices=[(1, '1385'), (2, '1386'), (3, '1387'), (4, '1388'), (5, '1389'), (6, '1390'), (7, '1391'), (8, '1392'), (9, '1393'), (10, '1394'), (11, '1395'), (12, '1396'), (13, '1397'), (14, '1398'), (15, '1399'), (16, '1400'), (17, '1401'), (18, '1402'), (19, '1403'), (20, '1404'), (21, '1405'), (22, '1406'), (23, '1407'), (24, '1408'), (25, '1409'), (26, '1410'), (27, '1411'), (28, '1412'), (29, '1413'), (30, '1414')], default=1, null=True, verbose_name='تا سال')),
            ],
            options={
                'verbose_name': 'سال',
                'verbose_name_plural': 'سال های تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='rank_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(help_text='بعنوان مثال: اعضای هیئت رئیسه', max_length=50, null=True, verbose_name='دسته بندی')),
                ('rank_type_order', models.PositiveSmallIntegerField(help_text='بعنوان مثال عدد 1 بالاترین درجه است', null=True, verbose_name='اولویت دسته بندی')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام سمت')),
                ('order', models.PositiveSmallIntegerField(help_text='بعنوان مثال عدد 1 بالاترین درجه است', null=True, verbose_name='اولویت سمت')),
                ('info', models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.years_list', verbose_name='سال تحصیلی')),
            ],
            options={
                'verbose_name': 'درجه',
                'verbose_name_plural': 'درجه های اعضای انجمن',
            },
        ),
        migrations.CreateModel(
            name='CecMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='نام نام خانوادگی')),
                ('avatar', models.ImageField(upload_to=app_main.models.cec_members_avatar_path, verbose_name='عکس پروفایل')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.rank_list', verbose_name='سمت')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.years_list', verbose_name='سال تحصیلی')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضای هیئت رئیسه و کادر',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9.,-]+$', 'تنها استفاده از حروف انگلیسی مجاز می\u200cباشد.')])),
                ('publish', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('show_author', models.BooleanField(default=True, verbose_name='نمایش نام نویسنده')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده'), (3, 'عدم تایید'), (4, 'پیش\u200cنویس')], default=1, null=True, verbose_name='وضعیت تایید پست')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'خبری'), (2, 'آموزشی'), (3, 'دانشجویی'), (4, 'انگیزشی'), (5, 'متفرقه'), (6, 'معرفی')], null=True, validators=[app_main.models.check_blog_states], verbose_name='دسته بندی')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='عنوان')),
                ('DateCreate', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('LastEdit', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین ادیت')),
                ('TimeCreate', models.TimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='ساعت ایجاد')),
                ('_DateCreate', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن')),
                ('image', models.ImageField(upload_to=app_main.models.blog_image_path, verbose_name='تصویر پست')),
                ('meta_description', models.TextField(max_length=160, null=True, verbose_name='محتوای متا\u200cتگ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست های بلاگ',
                'ordering': ('_DateCreate',),
            },
        ),
    ]
