# Generated by Django 2.2.5 on 2020-10-25 21:57

import app_main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خبری'), (2, 'آموزشی'), (3, 'دانشجویی'), (4, 'انگیزشی'), (5, 'متفرقه'), (6, 'معرفی'), (7, 'علمی')], null=True, validators=[app_main.models.check_blog_states], verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='AttachmentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام فایل')),
                ('file', models.FileField(null=True, upload_to=app_main.models.attachment_files_path, verbose_name='فایل')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_main.Blog', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل های ضمیمه شده در بلاگ',
            },
        ),
    ]
