# Generated by Django 2.2.5 on 2020-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20201025_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfiles',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='نام فایل'),
        ),
    ]
